### PR TITLE
userID-topLeft-#171

### PR DESCRIPTION
**Pull request by CalvinFronda**
for bug #171

### CODE REVIEW

**Comment by NeilAllavarpu** [comment]
Was anything changed?

**Comment by NeilAllavarpu** [comment]
Still not seeing changes

**Comment by CalvinFronda** [comment]
changes are on profileHeading.js. The student ID is on the left side.

Screen Shot 2020-02-05 at 10 10 22 PM

**Comment by dhuangg** [comment]
10/10. you're on a roll! 😀🍥

**Comment by dhuangg** [comment]
This looks good. Make sure to merge with the updates on dev first. This is a couple of commits behind.

**Comment by CalvinFronda** [comment]
Should be merged with dev

**Pull request merged**
