### PR TITLE
Selectparent

### PR DESCRIPTION
**Pull request by jsflca2012**

### CODE REVIEW

**Comment by dhuangg** [comment]
@jsflca2012 also, you HAVE TO merge the latest version of stage prior to making a pull request. You also shouldn't be merging this into the "master" branch. Everything needs to go onto "development" and "stage" first.

**Comment by jsflca2012** [comment]
@dhuangg fixed.

**Comment by dhuangg** [comment]
I merged development into this branch. make sure to merge regularly so you don't have to deal with large complex merge conflicts. 

Also your changes aren't working. I didn't look too deep into it, but figure out why the select field is so far down. 
Screen Shot 2020-01-04 at 2 52 59 PM

**Comment by dhuangg** [comment]
@jsflca2012 I've fixed this ticket myself. I'm going to close it. This is what it looks like now: 
Screen Shot 2020-01-04 at 7 17 18 PM

**Pull request closed without merging**
