### PR TITLE
Hamburger menu color

### PR DESCRIPTION
**Pull request by rgedwill**

### CODE REVIEW

**Comment by rgedwill** [comment]
Issue #440 (A004)

**Comment by CalvinFronda** [comment]
Its still black

Screen Shot 2020-08-06 at 10 45 14 PM

If its just a color change, I'd just change it with inline styles like this. ```style={{ color: "white" }}```

**Comment by dhuangg** [comment]
sorry, i didnt read this carefully enough. @Ryan if this is outside of the
Mui Theme Provider it may be why the color isn't being applied. if that's
the case then just push up @Calvin's temp fix

**Comment by dhuangg** [comment]
@rgedwill this is still black for me 
Screen Shot 2020-08-10 at 5 39 01 PM

**Pull request merged**
